version: '3.8'

networks:
  rede-da-sheila:
    driver: bridge

services:
  db:
    image: postgres:15
    container_name: fake-shop-db
    restart: always
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: Pg1234
      POSTGRES_DB: ecommerce
    ports:
      - "8214:5432"
    networks:
      - rede-da-sheila
    volumes:
      - fake-shop-db-data:/var/lib/postgresql/data

  app:
    build:
      context: ./src
    container_name: fake-shop-app
    restart: always
    env_file:
      - ./src/.env
    ports:
      - "8217:8217"
    depends_on:
      - db
    networks:
      - rede-da-sheila
    volumes:
      - ./src:/app

volumes:
  fake-shop-db-data:
