services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "8212:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - JAVA_OPTS=-Xms256m -Xmx768m
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  sonarqube_data:
  sonarqube_extensions:
