name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o Código
        uses: actions/checkout@v4.2.2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção e Envio da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src # Confirme que Dockerfile, requirements.txt, entrypoint.sh estão dentro de 'src'
          push: true
          file: ./src/Dockerfile
          tags: |
            sheila421/fake-shop-app:latest
            sheila421/fake-shop-app:v${{ github.run_number }}

  deploy: # Job de deploy (agora sem sonar-analysis)
    needs: CI # Depende do job CI
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: | # Usando | para scripts multi-linha
            echo "Iniciando deploy da aplicação..."
            docker pull sheila421/fake-shop-app:latest
            docker stop fake-shop-app || true
            docker rm fake-shop-app || true
            docker stop fake-shop-db || true
            docker rm fake-shop-db || true
            docker network rm rede-da-sheila || true
            docker network create rede-da-sheila || true
            docker volume create fake-shop-db-data || true

            # Inicia o contêiner do banco de dados (todo em uma linha Bash)
            docker run -d --name fake-shop-db --network rede-da-sheila -e POSTGRES_USER=ecommerce -e POSTGRES_PASSWORD=Pg1234 -e POSTGRES_DB=ecommerce -p 8214:5432 -v fake-shop-db-data:/var/lib/postgresql/data postgres:15

            echo "Aguardando banco de dados..."
            # Loop de verificação do banco de dados (estrutura Bash em múltiplas linhas do YAML)
            until docker exec fake-shop-db pg_isready -h localhost -p 5432 -U ecommerce; do
              echo "Banco não pronto ainda..."
              sleep 5
            done
            echo "Banco de dados 'fake-shop-db' está pronto!"
            sleep 20 # Dar um tempo extra para o DB inicializar completamente

            DB_INTERNAL_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' fake-shop-db)
            echo "DEBUG: IP interno do fake-shop-db para migração e aplicação: $DB_INTERNAL_IP"

            # Executa as migrações do banco de dados (todo em uma linha Bash)
            # CORREÇÃO: Usar 'flask db upgrade' em vez de 'migrate'
            docker run --rm --network rede-da-sheila --env-file /home/aluno/sheila_alves/.env -e FLASK_APP=index.py -e DB_HOST="${DB_INTERNAL_IP}" sheila421/fake-shop-app:latest flask db upgrade
            MIGRATION_STATUS=$? # Captura o status de saída do comando anterior
            
            # Condicional para verificar o status da migração (estrutura Bash em múltiplas linhas do YAML)
            if [ $MIGRATION_STATUS -ne 0 ]; then
              echo "ERRO: Migrações do banco de dados falharam! Verifique os logs da execução do workflow para mais detalhes."
              exit $MIGRATION_STATUS
            fi

            # Inicia o contêiner da aplicação (todo em uma linha Bash)
            # CORREÇÃO: Usar porta 8213:8213 (conforme as últimas correções)
            docker run -d --name fake-shop-app --network rede-da-sheila --env-file /home/aluno/sheila_alves/.env -e DB_HOST="${DB_INTERNAL_IP}" -p 8213:8213 sheila421/fake-shop-app:latest /app/entrypoint.sh

            sleep 5 # Dar um tempo para a aplicação iniciar
            docker exec fake-shop-app env > /tmp/app_env_vars.txt # Salva variáveis de ambiente da aplicação
            docker logs fake-shop-app > /tmp/app_logs.txt # Salva logs da aplicação

            echo "DEBUG: Logs e variáveis de ambiente salvos em /tmp/app_logs.txt e /tmp/app_env_vars.txt no servidor."
            echo "DEBUG: Acesse o servidor via SSH e use 'cat /tmp/app_env_vars.txt' e 'cat /tmp/app_logs.txt' para verificar."



